# Generated by Django 4.2.1 on 2023-05-16 20:53

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("MyPet_site", "0002_mypettext_board_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mypettext",
            name="board_text",
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
