# Generated by Django 4.2.1 on 2023-05-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MyPet_site", "0004_mypettext_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mypettext",
            name="img_url",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
