# Generated by Django 4.2.1 on 2023-05-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MyPet_site", "0007_rename_pettext_comment_pet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="rate",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="writer",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
