# Generated by Django 4.2.1 on 2023-05-17 11:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("MyPet_site", "0008_alter_comment_comment_alter_comment_rate_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comment",
            new_name="Comments",
        ),
    ]
