# Generated by Django 4.2.1 on 2023-05-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MyPet_site", "0011_alter_comment_writer"),
    ]

    operations = [
        migrations.AddField(
            model_name="mypettext",
            name="pet_title",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="mypettext",
            name="pet_video",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
