# Generated by Django 4.2.1 on 2023-05-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MyPet_site", "0012_mypettext_pet_title_mypettext_pet_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mypettext",
            name="pet_video",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
